# Generated by Django 4.1.7 on 2023-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_poduct_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
