# Generated by Django 4.1.7 on 2023-04-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stripe_poduct_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_poduct_price_id',
            new_name='stripe_product_price_id',
        ),
    ]
